### ISSUE TITLE
没有下载按键

### ISSUE THREAD

**Issue by TinyKing001** [ltaoo/wx_channels_download#1]
![Snipaste_2024-11-01_16-51-23](https://github.com/user-attachments/assets/906e842c-ec95-4115-ab58-2bda97b9cbf5)

**Comment by ltaoo** [comment]
是所有视频都没有下载按钮吗？
我这里试了有下载按钮的。或者把视频名称发一下，我试试看。

**Comment by MrHua** [comment]
![微信图片_20241102160621](https://github.com/user-attachments/assets/11c6f9bc-6d25-4cec-953b-ed8f66bc0270)
我这里一样的情况，所有的视频都没有下载按钮。 微信 3.9.12.17。Windows 11 24H2 专业版 	，操作系统版本	26100.2152

**Comment by ltaoo** [comment]
试试看 24110203 这个版本，增加了一些调试信息，然后把终端截个图我看下。

**Comment by MrHua** [comment]
详情页下载功能已正常，通过以下两个入口进入视频号主页、个人中心，页面均空白，
![87704228b19ac35ef3fef5d5fbd54bf](https://github.com/user-attachments/assets/42bfbc66-365a-478e-ad22-9eea89f9ed6c)
![1975467c6accf8f86b98d19f76c1850](https://github.com/user-attachments/assets/f563d478-ecad-4dd6-849c-1e932393fa17)
![87704228b19ac35ef3fef5d5fbd54bf](https://github.com/user-attachments/assets/d360e5b6-ff8c-49f2-a6c4-8a3d078d1b27)

**Comment by MrHua** [comment]
![2cd20d28f39c2c0b15515c73914b217](https://github.com/user-attachments/assets/71413abb-583c-4101-afaf-d7979d4f091e)

**Comment by ltaoo** [comment]
某些页面空白的问题，在新版本 241103 修复了
