### ISSUE TITLE
一直在转，刷新几次也不出来

### ISSUE THREAD

**Issue by zaxchou** [ltaoo/wx_channels_download#11]
![微信截图_20241115164915](https://github.com/user-attachments/assets/dd640375-c653-4c2f-88fe-9ebee012d506)
![微信截图_20241115164926](https://github.com/user-attachments/assets/a4ddcaa7-74d1-4f94-847b-72fc10cbf1b3)

**Comment by zaxchou** [comment]
![微信截图_20241115165115](https://github.com/user-attachments/assets/b1862ea5-382f-414b-b693-3cf2527234b0)
换了个公开视频。
前面那个是群课程视频

**Comment by ltaoo** [comment]
我没下载过群课程视频，确实可能有问题。

公开视频，用最新 241115 版本，试试这样的步骤

1、把视频分享到自己的「文件传输助手」
2、关掉所有视频号页面
3、打开本工具
4、从「文件传输助手」打开视频
5、点击下载

如果这样还是不行，把视频链接复制发这里，我试试看。

**Comment by zaxchou** [comment]
谢谢 ，我确实试了还是解密失败。
视频地址是这个https://channels.weixin.qq.com/web/pages/feed?oid=yVZKq1WuGKE&amp;nid=Yc63FiB6Tus&amp;context_id=33-9-141-Wbb5fced1795a78101731663526118&amp;entrance_id=1002&amp;xlab_enable_finder_home=1&amp;req_time=1731660640&amp;preload_id=7285338944437051878&amp;exportkey=n_ChQIAhIQQutN62y6lp4wsN0EKx0k%2BRLlAQIE97dBBAEAAAAAAOIlCGiQMPYAAAAOpnltbLcz9gKNyK89dVj0zhhUgYGiskQVQly%2B%2Bwtx5iSwCOW18JEngVZq%2BlHayoMFKLbpklJTKJWAi%2Bg17xONKDnCTgrqtI4iSIACf8hywMB2xQ8cHAGyWxBahT1uWOt2cEB%2F4hynQrW5r5sVl2RBhyBO1YORN3AtBVyEpevOuHvYJCCp4piOuOdtjl2md9RwkTeVgJhMwpHDn1sI55OeegdnEcUksIKJb89u191MviT4YVfFrkefHNSSZE9gQgfUde3dA73loqVjcXeWeSM%3D&amp;pass_ticket=YQnhP3a4VR8apfGZoNUu4EPSVUBBQnlf2Vf%2BrGnAzZ7PZzF6iU7jNfbNai5sEq5suYlk%2BVpnJ9FImIPSo%2F8PNg%3D%3D&amp;wx_header=0










Zax&nbsp;Chou
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月15日(周五) 下午5:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ltaoo/wx_channels_download] 一直在转，刷新几次也不出来 (Issue #11)




 
我没下载过群课程视频，确实可能有问题。
 
公开视频，用最新 241115 版本，试试这样的步骤
 
1、把视频分享到自己的「文件传输助手」
 2、关掉所有视频号页面
 3、打开本工具
 4、从「文件传输助手」打开视频
 5、点击下载
 
如果这样还是不行，把视频链接复制发这里，我试试看。

**Comment by ltaoo** [comment]
使用最新 24111501 版本试试

**Comment by zaxchou** [comment]
> 使用最新 24111501 版本试试

h还是不行

**Comment by ltaoo** [comment]
终端截个图看看，我这里显示这样，可以正常下载

![image](https://github.com/user-attachments/assets/29cee542-c49c-44c8-b085-1d3b354ec91c)

**Comment by ltaoo** [comment]
关掉微信再试试，是缓存没有更新导致的。

步骤

1、把视频分享到自己的「文件传输助手」
2、关掉微信
3、打开微信，然后打开本工具
4、从「文件传输助手」打开视频
5、点击下载

**Comment by zaxchou** [comment]
> 关掉微信再试试，是缓存没有更新导致的。
> 
> 步骤
> 
> 1、把视频分享到自己的「文件传输助手」 2、关掉微信 3、打开微信，然后打开本工具 4、从「文件传输助手」打开视频 5、点击下载

视频号确实可以了，很感谢。其余就是群里视频号也能下载就更好了 ，就到注入下载2按钮就停了。这个地址不知道怎么给你，如果可以加我微信(5177135)我转发给你。
![微信截图_20241116123402](https://github.com/user-attachments/assets/e9295f6b-1782-4a73-843e-a4341d1ccb52)
![微信图片_20241116123415](https://github.com/user-attachments/assets/e1912f0c-7f68-4a76-8b91-7c4b7bfccdd2)
