### ISSUE TITLE
一直提示下载中

### ISSUE THREAD

**Issue by yzgzspzb** [ltaoo/wx_channels_download#13]
![微信图片_20241125191709](https://github.com/user-attachments/assets/91bc3aad-4626-4489-bc9b-19170525e2ba)

**Comment by ltaoo** [comment]
刚刚用最新版 24111501 这个试了，可以正常下载的。

如果视频很长，多等待一会，现在没有做进度提示。

还是不行的话，视频链接复制到这里，我看看

**Comment by yzgzspzb** [comment]
> 刚刚用最新版 24111501 这个试了，可以正常下载的。
> 
> 如果视频很长，多等待一会，现在没有做进度提示。
> 
> 还是不行的话，视频链接复制到这里，我看看

https://channels.weixin.qq.com/web/pages/feed?oid=xsA3sxr9GQU&nid=ke9zkVyHhjE&context_id=33-9-141-Wa27358b8c5a0635b1732599103173&entrance_id=1002&xlab_enable_finder_home=1&req_time=1731378381&preload_id=8255609655745218020&exportkey=n_ChQIAhIQhM1agD7K4xJoaIY5LNyqcRLyAQIE97dBBAEAAAAAALwwBF0pPugAAAAOpnltbLcz9gKNyK89dVj00C9t6W2Y5%2F6LBJy9SC2yqyy2Xc21m5RK%2BKhRM%2BgXuRHxQx6XZAUsNlg1ck6CyJ9wSaus1G%2B5Cdzr%2Bd8EiaLqzP9bE9fMDrLm7hML7Jo9VGE2AzjzCn8dwG%2FUmDqPZI8C6aVWwG6CJv0jHEdq%2FOhYBCzy7BLcY%2FJC%2FTpVwL3d3uEW5VUVp%2F5mXPG%2BwO3VmuC%2B7eNL%2FXBMMyxCfgdbsakJ4PKd8a6UM9OB1teXIzyFpDOSxA9d8Nq%2BhLxOIHW5Fo%2F8cv0sB7yDKJfk5dFz&pass_ticket=GFs4E6jdta53MsaLXmT0cgA7wbhEnyqaB%2FFjBNRG412QiBagpoJawMqShLyBZqfn69f0vAITjthAEynBMIP%2B1Q%3D%3D&wx_header=0

**Comment by ltaoo** [comment]
可以下载，默认下载按钮会下载 30MB 的文件，等待大概 10s 就好了。下载原始视频会下载 270MB 的文件，等待大概 1 分钟。

**Comment by yzgzspzb** [comment]
你好，运行测试了，启动wx_video_download_v24111501.exe ，看截图，在视频下方的下载按钮点击后一直显示下载无反应




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ltaoo/wx_channels_download"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月26日(星期二) 中午1:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ltaoo/wx_channels_download] 一直提示下载中 (Issue #13)





 
可以下载，默认下载按钮会下载 30MB 的文件，等待大概 10s 就好了。下载原始视频会下载 270MB 的文件，等待大概 1 分钟。
