### ISSUE TITLE
直播回放无法下载

### ISSUE THREAD

**Issue by cethink** [ltaoo/wx_channels_download#15]
视频有两个多小时

**Comment by ltaoo** [comment]
暂时没有支持回放下载的计划，你可以把视频链接贴这里，后续有时间我会考虑。

**Comment by cethink** [comment]
视频号没有链接啊🤔

**Comment by ltaoo** [comment]
241216 版本支持了，但是我试了一个 20 分钟的直播回放，下载下来有 1.2GB，要下载 8 分钟，如果网速不好估计更久。

**Comment by cethink** [comment]
神一般的下载器，可以了 👍 就是选第一个可下载项下载的视频有点大，有几G，其他没试，谢谢大佬！
