### ISSUE TITLE
关闭窗口进程未退出

### ISSUE THREAD

**Issue by cethink** [ltaoo/wx_channels_download#16]
![image](https://github.com/user-attachments/assets/78446e80-f5ec-41b3-902f-d1e12d44a521)

**Comment by ltaoo** [comment]
没有复现，能详细说明下步骤吗，比如打开，然后 Ctrl + C，等待自动关闭。还是打开，下载几个视频后，点击右上角关闭窗口，等待自动关闭 等等。

**Comment by cethink** [comment]
我只操作了直播回放，应该是直播回放的问题

**Comment by cethink** [comment]
241216 没有发现问题 👍
