### ISSUE TITLE
用不起来，请问是什么原因?

### ISSUE THREAD

**Issue by gujishe** [ltaoo/wx_channels_download#2]
10月30日的版本问题：
点击下载弹出
<img width="1127" alt="截图_20241101211457" src="https://github.com/user-attachments/assets/9d3e54ca-a042-403c-894a-dc44a8ac1f7e">
申请恢复访问后点击下载进入网址https://finder.video.qq.com/251/20302/stodownload?encfilekey=6xykWLEnztKcKCJZcV0rWCM8ua7DibZkibqXGfPxf5lrpGXBMcIk84drSPbGKXicq8rv7EU7WbJ2Z1HfgTVPbKxIKaickQb6LC3Mia78tR8oNtia9rVvZuSPNZsG2uibOurXw0cqrYjKyfwibxOSDcDuEgGmKsbuPD28eaq3UMHbwpMFoEM&a=1&bizid=1023&dotrans=0&hy=SH&idx=1&m=a1258eb247133ee76e0146ed5cc9ecc3&web=1&token=6xykWLEnztJALj7BIfsmAicdHv1ZIVYbqu9tQYfxblcKKeRciaiaPYB60F8SaEceu8gorhRqgce46vKXiaVSgOkXvZy7pPmDxHN9xPrlqPibHMfMuxgZnJruxEFb9vnRMrDHI&basedata=CAASAA&sign=AOhnoC56uUcL4AQvliDwxXNViAJaquS9tMjuQSu_sRVcayjHCkqGwMg5j6GXWw_Mwu4qyzokzro2l1e64PFA5w&ctsc=141&extg=8f0000&ftype=101&svrbypass=AAuL%2FQsFAAABAAAAAAAfcH4RU1UZxXYVoiMjZxAAAADnaHZTnGbFfAj9RgZXfw6VvmMdIfhVY8SG8rB9QzgIB1gA%2BRfbq7v85KyYL%2FahYoPSm3Qqurdghlc%3D&svrnonce=1730356130
<img width="1219" alt="截图_20241101211732" src="https://github.com/user-attachments/assets/576e9f12-1006-40c9-a647-23f81b3d5e1c">
复制网址到下载器下载的MP4文件播放提示错误
<img width="564" alt="截图_20241101212013" src="https://github.com/user-attachments/assets/6a073a75-272d-4fc7-9c32-5f37dad94e7c">
<img width="602" alt="截图_20241101212040" src="https://github.com/user-attachments/assets/183737e9-22d8-42b1-90ea-bbe2cbb693a4">

10月31版本问题如下：
点击下载没反应，软件提示
<img width="786" alt="111111111111111" src="https://github.com/user-attachments/assets/978fbb4a-b073-4d29-83bd-5647ceadbd38">

11月1日版本，点击下载，直接下载的压缩包。压缩包解压提示错误，
<img width="1190" alt="截图_20241101210528" src="https://github.com/user-attachments/assets/c006858e-49e5-44c8-9817-507ed14b8b57">

<img width="483" alt="截图_20241101210253" src="https://github.com/user-attachments/assets/dd207640-3dbd-4f01-addd-e5207a0150cc">
<img width="690" alt="111111111111111" src="https://github.com/user-attachments/assets/1d190d20-8846-496f-bc69-71c0ad02f03d">

**Comment by ltaoo** [comment]
测试了下，的确是 bug。

之前没下载过超过 2 分钟的视频，这种时间太长的视频，需要完整播放完之后，才能下载。
我看下怎么解决这个问题。

**Comment by gujishe** [comment]
还是不行，而且最新版本的 下载按钮都没有了。可否加个微信 方便反馈，daoist1234

**Comment by gujishe** [comment]
我知道了，10月30号的版本，要用另外一个软件解密一下就可以打开了。所以还是建议点击下载那里 直接弹出地址来让复制就可以。因为腾讯会屏蔽了地址 无法跳转。

**Comment by gujishe** [comment]
后面10月31日以及11月1日的两个版本都无法使用

**Comment by ltaoo** [comment]
24110203 版本在「更多」增加了「下载视频」按钮。
