### ISSUE TITLE
开启下载代理之后无法进入直播间，页面一直缓冲。

### ISSUE THREAD

**Issue by MrHua** [ltaoo/wx_channels_download#5]
![image](https://github.com/user-attachments/assets/075e96ed-7207-491f-975b-17ad353442fc)
![1730726561376](https://github.com/user-attachments/assets/bd36b93b-54c6-4959-91c6-7279dee5b469)
![image](https://github.com/user-attachments/assets/9e90e2a3-aa55-4b8c-8d74-3365abf41df5)

**Comment by ltaoo** [comment]
241104 版本修复了，可以下载试试看。

**Comment by Eyion** [comment]
能自动监控直播并录制吗
