### ISSUE TITLE
下载的视频无法播放，导入编辑软件提示已损坏

### ISSUE THREAD

**Issue by nanpa** [ltaoo/wx_channels_download#7]
问题如题

**Comment by ltaoo** [comment]
我刚刚试了下 241104 版本，下载下来的视频可以正常播放的。
可否控制台截图贴一下，视频链接也复制给我
![image](https://github.com/user-attachments/assets/57ea88d7-c5a1-4924-9e89-dcc52ea24c3d)

**Comment by nanpa** [comment]
https://channels.weixin.qq.com/web/pages/feed?oid=yOUAEev3GWk&amp;nid=J1DV5Vb_mMg&amp;context_id=33-9-141-W3aff596111cd94f51730860179214&amp;entrance_id=1002&amp;xlab_enable_finder_home=1&amp;req_time=1730860122&amp;preload_id=4380187855332748082&amp;exportkey=n_ChQIAhIQOFNgpGzmmo807ABdc9uJaxLkAQIE97dBBAEAAAAAAFN3Ncu3PUYAAAAOpnltbLcz9gKNyK89dVj0FKFUkEThojju2fp3Fi4Iy04IxZXL%2BtP0cg54WQCzErXIXvgB%2BdD%2BEpv0nhr%2FyqBL4cGUG30czwPIOz0lvm6Mvaj7fXpVgsKwYR6eC1s%2FP4SanV1EeQzKnLzqhKhRKN7qbgOhxkmuSSrGuTBFz3UKDi1JeBK0erxr9Z6GuvmWJHSd2Nu%2FZm6DiKz8ru%2BVDFrMZQWQ7Nc9VXxRoLcW%2FB7MPAV613I%2FjbzJFRx9EBpkjhxHBTqiJQaMdU3zTLr%2BXw%3D%3D&amp;pass_ticket=vBO1ACFjkjMOSsUcN%2BgLZpd0FPBhr0N9bgT7F9fpVQPsunR5Jw7FWRNY7wlfBzeq6Bcwy%2BTYGwgNagZaSXmRgg%3D%3D&amp;wx_header=0









------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月6日(星期三) 中午11:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ltaoo/wx_channels_download] 下载的视频无法播放，导入编辑软件提示已损坏 (Issue #7)














 
我刚刚试了下 241104 版本，下载下来的视频可以正常播放的。
 可否控制台截图贴一下，视频链接也复制给我
 image.png (view on web)

**Comment by ltaoo** [comment]
现在有一个很奇怪的 bug，有些视频确实下载下来播放不了。但是复制链接后，在新 tab 中打开，下载下来就可以打开。

![image](https://github.com/user-attachments/assets/47cd9663-5e8a-4a59-8ea7-e68e91079414)

把链接复制到这里后打开，再下载，下载下来的视频可以正常播放。

**Comment by ltaoo** [comment]
241106 版本应该解决了，可以下载这个版本试试看。

**Comment by nanpa** [comment]
新版本出现解密失败，把所有窗口关闭后再开也是一样

**Comment by ltaoo** [comment]
我也不知道为什么... 我用 241106 版本是正常的

https://github.com/user-attachments/assets/9ac33af7-3498-4301-8668-9d465b429ed5

**Comment by ltaoo** [comment]
我又发了一个 241107 版本，可以试试这个，可能可以解决。如果解决不了，我也没办法了。
