### ISSUE TITLE
今天用一直出现下载中

### ISSUE THREAD

**Issue by 02qbx** [ltaoo/wx_channels_download#9]
![Uploading 微信截图_20241112113442.png…]()

**Comment by ltaoo** [comment]
我刚刚用 241107 版本试了，可以正常下载的。

![image](https://github.com/user-attachments/assets/57ea88d7-c5a1-4924-9e89-dcc52ea24c3d)

点击这里，把视频链接复制给我，我试试看。

**Comment by 02qbx** [comment]
https://channels.weixin.qq.com/web/pages/feed?eid=export%2FUzFfAgtgekIEAQAAAAAAzQQARQdttAAAAAstQy6ubaLX4KHWvLEZgBPExqN8C0BrZbCAzNPgMIoBkkmr46zAx8BUS7qLQYFA&context_id=5-1-144-W116f52247801316f1731392304866&entrance_id=1006&xlab_enable_finder_home=1&preload_id=7926589809546536017&exportkey=n_ChQIAhIQfEooa1uanO3p1wDzfBk9dBLyAQIE97dBBAEAAAAAACrGCtwdjQwAAAAOpnltbLcz9gKNyK89dVj0f3KfKNYKObGu6uPLT4N9dMpCoQrpmFwrn9hSftNMrMlUWarqk3T6HHQFYVxcWCjZXyyJGsPd069lLOaiudV84R%2B%2Bs1Wu4OvdajlF0p7XasEfLX9lcPD9GY5xA%2FClTzrZdoX5E4NqPsIYDxq05MWbeoFx6vKZA7wUBbFv2%2BYECCP5mMSSIskKrIiu3istmUuUfeycxViDBRmRFzCi4CTBFvWly6t%2F7LTk8XVDgHCa0vHoLS7%2BW%2B8%2FrVvyziS8WiqPZiT%2B%2BDJ7U9p2sdwd&pass_ticket=LqoQI32sVoQQpZ3IS7RbavqlQI1WT9e6UtSWhANLkpfDkiXaz20l%2Fr12WbHkTJ5VNLoWMBnphTPhISpU0XGJVA%3D%3D&wx_header=0

**Comment by ltaoo** [comment]
可以正常下载，视频时长越长，「下载中」显示得越久，所以要多等待一会。

准确的下载进度暂时没准备做。


https://github.com/user-attachments/assets/3f937152-2d5f-4ac7-8447-fca4e1f5acd1

**Comment by 02qbx** [comment]
好吧

**Comment by Aiurvie** [comment]
> 可以正常下载，视频时长越长，「下载中」显示得越久，所以要多等待一会。
> 
> 准确的下载进度暂时没准备做。
> 
>  _xWT111.mp4

下载进度不用复杂，页面显示个大概也行啊

**Comment by ltaoo** [comment]
250215 版本在终端显示下载进度了
